# Generated by Django 4.0.2 on 2022-03-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesapi',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='moviesapi',
            name='movie_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
